/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programrental;

import Database.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDesktopPane;
import models.Kendaraan;

/**
 *
 * @author Ghazi
 */
public class FormDaftarKendaraan extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormDaftarKendaraan
     */
    Boolean isEdit;
    JDesktopPane jdp = new JDesktopPane();
    Integer k_id;
    public FormDaftarKendaraan(JDesktopPane dp, Boolean stat, Integer id) {
        initComponents();
        jdp = dp;
        k_id = id;
        if(stat){
            isEdit = true;
            generateData(k_id);
        } else {
            isEdit = false;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mMerk = new javax.swing.JTextField();
        mJenis = new javax.swing.JTextField();
        mHargaPerHari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM DAFTAR KENDARAAN");

        jLabel2.setText("Merk");

        jLabel3.setText("Jenis");

        jLabel4.setText("Harga Per Hari");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(70, 70, 70)
                        .addComponent(mMerk))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(69, 69, 69)
                        .addComponent(mJenis))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(mHargaPerHari))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(mHargaPerHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String merk = mMerk.getText();
        String jenis = mJenis.getText();
        Integer harga_per_hari = Integer.parseInt(mHargaPerHari.getText());
        
        if(isEdit){
            String set = "merk = '" + merk + "', jenis = '" + jenis + "', harga_per_hari = '" + harga_per_hari + "'";
            Database.updateData("daftar_kendaraan", set, k_id);
            DaftarKendaraan v = new DaftarKendaraan(jdp);
            jdp.add(v);
            v.setVisible(true);
            this.dispose();
        } else {
            String attr = "(merk, jenis, harga_per_hari)";
            String value = "('"+merk+"','"+jenis+"','"+harga_per_hari+"')";
            Database.insertData("daftar_kendaraan", attr, value);
            DaftarKendaraan v = new DaftarKendaraan(jdp);
            jdp.add(v);
            v.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void generateData(Integer id){
        String search = "id = " + id;
        ResultSet rs = Database.searchData("daftar_kendaraan", search);
        try{
            while(rs.next()){
                mMerk.setText(rs.getString("merk"));
                mJenis.setText(rs.getString("jenis"));
                mHargaPerHari.setText(rs.getInt("harga_per_hari")+"");
            }
        } catch(SQLException ex){
            ex.getMessage();
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField mHargaPerHari;
    private javax.swing.JTextField mJenis;
    private javax.swing.JTextField mMerk;
    // End of variables declaration//GEN-END:variables
}
