/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programrental;

/**
 *
 * @author Ghazi
 */

import Database.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

public class FormDaftarCustomer extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormDaftarCustomer
     */
    Boolean isEdit;
    JDesktopPane jdp = new JDesktopPane();
    Integer k_id;
    String tableName = "daftar_customer";
    public FormDaftarCustomer(JDesktopPane dp, Boolean stat, Integer id) {
        initComponents();
        jdp = dp;
        k_id = id;
        if(stat){
            isEdit = true;
            generateData(k_id);
        } else {
            isEdit = false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mNama = new javax.swing.JTextField();
        mAlamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbTipeId = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mNoId = new javax.swing.JTextField();
        mNoHp = new javax.swing.JTextField();
        mUmur = new javax.swing.JTextField();

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Tipe Identitas");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM DAFTAR CUSTOMER");

        cbTipeId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KTP", "SIM", "Paspor" }));

        jLabel5.setText("No. Identitas");

        jLabel6.setText("No. Handphone");

        jLabel7.setText("Umur");

        mNoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNoHpActionPerformed(evt);
            }
        });

        mUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUmurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(70, 70, 70)
                        .addComponent(mNama))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(64, 64, 64)
                        .addComponent(mAlamat))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(cbTipeId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(mNoId))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(mUmur)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(23, 23, 23)
                        .addComponent(mNoHp)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbTipeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mNoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(mUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nama = mNama.getText();
        String alamat = mAlamat.getText();
        String id_type = cbTipeId.getSelectedItem().toString();
        String no_id = mNoId.getText();
        String no_hp = mNoHp.getText();
        String umur = mUmur.getText();
        
        if(formFill() != true){
            //formFill();
        } else {
            if(isEdit){
                String set = "nama = '" + nama + "', alamat = '" + alamat + "', id_type = '" + id_type + "', no_id = '" + no_id + "', no_hp = '" + no_hp + "', umur = '" + umur + "'";
                Database.updateData(tableName, set, k_id);
                DaftarCustomer v = new DaftarCustomer(jdp);
                jdp.add(v);
                v.setVisible(true);
                this.dispose();
            } else {
                String attr = "(nama, alamat, id_type, no_id, no_hp, umur)";
                String value = "('"+nama+"','"+alamat+"','"+id_type+"','"+no_id+"','"+no_hp+"','"+umur+"')";
                Database.insertData(tableName, attr, value);
                DaftarCustomer v = new DaftarCustomer(jdp);
                jdp.add(v);
                v.setVisible(true);
                this.dispose();
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private Boolean formFill(){
        Boolean stat;
        if(mNama.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Nama harus diisi!");
            stat = false;
        } else if(mAlamat.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Alamat harus diisi!");
            stat = false;
        } else if(mNoId.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "No Id harus diisi!");
            stat = false;
        } else if(mNoHp.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "No HP harus diisi!");
            stat = false;
        } else if(mUmur.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Umur harus diisi!");
            stat = false;
        } else {
            stat = true;
        }
        
        return stat;
    }
    
    private void mNoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mNoHpActionPerformed

    private void mUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mUmurActionPerformed

    private void generateData(Integer id){
        String search = "id = " + id;
        ResultSet rs = Database.searchData(tableName, search);
        try{
            while(rs.next()){
                mNama.setText(rs.getString("nama"));
                mAlamat.setText(rs.getString("alamat"));
                cbTipeId.setSelectedItem(rs.getString("id_type"));
                mNoId.setText(rs.getString("no_id"));
                mNoHp.setText(rs.getString("no_hp"));
                mUmur.setText(rs.getString("umur"));
            }
        } catch(SQLException ex){
            ex.getMessage();
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTipeId;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField mAlamat;
    private javax.swing.JTextField mNama;
    private javax.swing.JTextField mNoHp;
    private javax.swing.JTextField mNoId;
    private javax.swing.JTextField mUmur;
    // End of variables declaration//GEN-END:variables
}
