/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programrental;

import Database.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import models.Customer;
import models.Kendaraan;
import models.Rental;

/**
 *
 * @author Ghazi
 */
public class FormDaftarRental extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormDaftarRental
     */
    Boolean isEdit;
    JDesktopPane jdp = new JDesktopPane();
    Integer k_id;
    ArrayList<Kendaraan> itemsKendaraan = new ArrayList<Kendaraan>();
    ArrayList<Customer> itemsCustomer = new ArrayList<Customer>();
    Integer hargaPerHari;
    String tableName = "daftar_rental";
    public FormDaftarRental(JDesktopPane dp, Boolean stat, Integer id) {
        initComponents();
        jdp = dp;
        k_id = id;
        generateKendaraan();
        generateCustomer();
        if(stat){
            isEdit = true;
            generateData(k_id);
        } else {
            isEdit = false;
        }
        mTotalHarga.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mTotalHariSewa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mTotalHarga = new javax.swing.JTextField();
        cbKendaraan = new javax.swing.JComboBox<>();
        cbCustomer = new javax.swing.JComboBox<>();
        mTanggalSewa = new com.toedter.calendar.JDateChooser();
        cbStatusSewa = new javax.swing.JComboBox<>();
        btnCekHarga = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM DAFTAR RENTAL");

        jLabel5.setText("Total Hari Sewa");

        jLabel6.setText("Status Sewa");

        jLabel7.setText("Total Harga");

        jLabel2.setText("Kendaraan");

        jLabel3.setText("Customer");

        jLabel4.setText("Tanggal Sewa");

        mTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTotalHargaActionPerformed(evt);
            }
        });

        cbKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKendaraanActionPerformed(evt);
            }
        });

        mTanggalSewa.setDateFormatString("yyyy-MM-dd");

        cbStatusSewa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Sedang Berjalan", "Selesai" }));

        btnCekHarga.setText("Cek Harga");
        btnCekHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCustomer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbKendaraan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mTotalHarga)
                            .addComponent(mTanggalSewa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbStatusSewa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mTotalHariSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCekHarga)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(mTanggalSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mTotalHariSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCekHarga))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbStatusSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(mTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Integer id_kendaraan = itemsKendaraan.get(cbKendaraan.getSelectedIndex()).getId();
        Integer id_customer = itemsCustomer.get(cbCustomer.getSelectedIndex()).getId();
        String tanggal_sewa = ((JTextField)mTanggalSewa.getDateEditor().getUiComponent()).getText();
        Integer total_hari_sewa = Integer.parseInt(mTotalHariSewa.getText());
        String status_sewa = cbStatusSewa.getSelectedItem().toString();
        Integer total_harga = Integer.parseInt(mTotalHarga.getText());
        
        
        if(formFill() != true){
            formFill();
        } else {
            if(isEdit){
                String set = "id_kendaraan = '" + id_kendaraan + "', id_customer = '" + id_customer + "', tanggal_sewa = '" + tanggal_sewa + "', total_hari_sewa = '" + total_hari_sewa + "', status_sewa = '" + status_sewa + "', total_harga = '" + total_harga + "'";
                Database.updateData(tableName, set, k_id);
                DaftarRental v = new DaftarRental(jdp);
                jdp.add(v);
                v.setVisible(true);
                this.dispose();
            } else {
                String attr = "(id_kendaraan, id_customer, tanggal_sewa, total_hari_sewa, status_sewa, total_harga)";
                String value = "('"+id_kendaraan+"','"+id_customer+"','"+tanggal_sewa+"','"+total_hari_sewa+"','"+status_sewa+"','"+total_harga+"')";
                Database.insertData(tableName, attr, value);
                DaftarRental v = new DaftarRental(jdp);
                jdp.add(v);
                v.setVisible(true);
                this.dispose();
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mTotalHargaActionPerformed

    private void btnCekHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekHargaActionPerformed
        // TODO add your handling code here:
        hargaPerHari = itemsKendaraan.get(cbKendaraan.getSelectedIndex()).getHargaPerHari();
        mTotalHarga.setText(Integer.parseInt(mTotalHariSewa.getText()) * hargaPerHari + "");
    }//GEN-LAST:event_btnCekHargaActionPerformed

    private void cbKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKendaraanActionPerformed
        // TODO add your handling code here:
        //
    }//GEN-LAST:event_cbKendaraanActionPerformed

    private Boolean formFill(){
        Boolean stat;
        if(((JTextField)mTanggalSewa.getDateEditor().getUiComponent()).getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Tanggal Harus diisi");
            stat = false;
        } else if(mTotalHariSewa.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Total hari sewa Harus diisi");
            stat = false;
        } else if(cbStatusSewa.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Status sewa Harus diisi");
            stat = false;
        } else if(mTotalHarga.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Total harga Harus diisi");
            stat = false;
        } else {
            stat = true;
        }
        return stat;
    }
    private void generateKendaraan(){
        itemsKendaraan.clear();
        ResultSet rs = Database.selectData("daftar_kendaraan");
        try{
            while(rs.next()){
               itemsKendaraan.add(new Kendaraan(rs.getInt("id"), rs.getString("merk"), rs.getString("jenis"), rs.getInt("harga_per_hari")));
               cbKendaraan.addItem(rs.getString("jenis"));
            }
        } catch(SQLException ex){
            ex.getMessage();
        }
    }

    private void generateCustomer(){
        itemsCustomer.clear();
        ResultSet rs = Database.selectData("daftar_customer");
        try{
            while(rs.next()){
               itemsCustomer.add(new Customer(rs.getInt("id"), rs.getString("nama"), rs.getString("alamat"), rs.getString("id_type"), rs.getString("no_id"), rs.getString("no_hp"), rs.getString("umur")));
               cbCustomer.addItem(rs.getString("nama"));
            }
        } catch(SQLException ex){
            ex.getMessage();
        }
    }
    
    private void generateData(Integer id){
        String search = "a.id = " + id;
        ResultSet rs = Database.generateRentalSearch(search);
        try{
            while(rs.next()){
               cbKendaraan.setSelectedItem(rs.getString("jenis"));
               cbCustomer.setSelectedItem(rs.getString("nama"));
               ((JTextField)mTanggalSewa.getDateEditor().getUiComponent()).setText(rs.getString("tanggal_sewa"));
               mTotalHariSewa.setText(rs.getInt("total_hari_sewa")+"");
               cbStatusSewa.setSelectedItem(rs.getString("status_sewa"));
               mTotalHarga.setText(rs.getString("total_harga"));
            }
        } catch(SQLException ex){
            ex.getMessage();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCekHarga;
    private javax.swing.JComboBox<String> cbCustomer;
    private javax.swing.JComboBox<String> cbKendaraan;
    private javax.swing.JComboBox<String> cbStatusSewa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.toedter.calendar.JDateChooser mTanggalSewa;
    private javax.swing.JTextField mTotalHarga;
    private javax.swing.JTextField mTotalHariSewa;
    // End of variables declaration//GEN-END:variables
}
